#!/bin/sh

PATH=/opt/sbin:/opt/bin:/opt/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

case $1 in
	start)
	/jffs/addons/young/nut.sh start wait
	;;
	stop)
	/jffs/addons/young/nut.sh stop
	;;
	restart)
	/jffs/addons/young/nut.sh restart
	;;
	check)
	/jffs/addons/young/nut.sh check
	;;
	*)
	echo "Usage: $0 {start|stop|restart|check}"
	;;
esac
