#!/bin/sh
# Entware startup script for all NUT services
# Place in /opt/etc/init.d and make the file executable

ENABLED=yes
PROCS=/jffs/addons/young/start-nut.sh
ARGS=
PREARGS=""
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /opt/etc/init.d/rc.func
